"""
===========================
RevAssets
===========================

Makes possible for python web apps to work with hashed static assets
generated by other tools like Gulp or Webpack.

It does so by reading the ``manifest.json`` generated by the revision tool.

"""
__version__ = '1.0.0'
